[project]
name = "christophernanna-me"
version = "0.1.0"
description = "Personal website and blog."
authors = [
    {name = "Christopher Hanna", email = "chris@christophernanna.me"},
]
dependencies = [
    "Flask",
    "python-dotenv",
]
[project.urls]
"Homepage" = "https://christophernanna.me"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
